import {useState} from 'react'
import Layout from '../../components/Layout'
import Seo from '../../components/Seo'
import ProductCard from '../../components/ProductCard'
import ProductArt from '../../components/ProductArt'
import products from '../../data/products.json'
export async function getStaticPaths(){return{paths:products.map(p=>({params:{slug:p.slug}})),fallback:false}}
export async function getStaticProps({params}){return{props:{product:products.find(p=>p.slug===params.slug)}}}
export default function Product({product}){const[n,setN]=useState('');const related=products.filter(p=>p.category===product.category&&p.slug!==product.slug).slice(0,4);const add=(key)=>{const list=JSON.parse(localStorage.getItem(key)||'[]');if(!list.includes(product.slug))list.push(product.slug);localStorage.setItem(key,JSON.stringify(list));setN(key==='cart'?'Добавлено в корзину':'Добавлено в избранное')};return <Layout><Seo title={`${product.name} | iDanny`} description={product.desc} canonical={`https://idanny.ru/product/${product.slug}`}/><section className="productPage"><div className="productGallery"><ProductArt category={product.category} big/></div><div className="productInfo"><span className="eyebrow">{product.stock}</span><h1>{product.name}</h1><p>{product.desc}</p><div className="chips big"><span>Цвет: {product.color}</span><span>Версия: {product.memory}</span><span>{product.categoryName}</span></div><div className="priceBig">{product.price}</div><button className="primary wide" onClick={()=>add('cart')}>Добавить в корзину</button><button className="secondary wide" onClick={()=>add('favorites')}>В избранное</button>{n&&<p className="success">{n}</p>}</div></section><section className="infoRow"><article><b>Оригинальная техника</b><span>Проверяемые конфигурации.</span></article><article><b>Проверка при получении</b><span>Модель, комплектность, внешний вид.</span></article><article><b>Доставка по России</b><span>Условия согласовываются до отправки.</span></article></section><section className="sectionHead"><h2>Похожие товары</h2></section><section className="grid">{related.map(p=><ProductCard key={p.slug} product={p}/>)}</section></Layout>}
